---
title: Aaron Zomback, filmmaker
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: aaronzomback@gmail.com
description: a site dedicated to presenting the work and ideas of aaron zomback
baseurl:
url:
twitter_username: jekyllrb
github_username: jekyll
theme: jekyll-theme-minimal
plugins:
- jekyll-feed
